# Generated by Django 4.1.5 on 2023-01-18 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.profile'),
        ),
    ]
