# Generated by Django 4.1.5 on 2023-01-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_profile_name_alter_profile_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRemind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(unique=True)),
                ('rem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api_app.remind')),
            ],
        ),
    ]
