# Generated by Django 4.1.5 on 2023-01-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_alter_currentremind_rem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.profile'),
        ),
    ]
