# Generated by Django 4.1.5 on 2023-01-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_alter_remind_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentremind',
            name='telegram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.profile'),
        ),
    ]
