# Generated by Django 4.1.5 on 2023-01-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_alter_currentremind_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='date_remind',
            field=models.DateField(blank=True, null=True),
        ),
    ]
