# Generated by Django 4.1.5 on 2023-01-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_remind_day_repeat_alter_remind_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='day_repeat',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
