# Generated by Django 4.1.5 on 2023-01-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_remove_remind_day_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remind',
            name='is_repeat',
        ),
        migrations.AddField(
            model_name='remind',
            name='day_repeat',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
