# Generated by Django 4.1.5 on 2023-01-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp_bot_app', '0006_remove_currentremind_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentremind',
            name='rem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exp_bot_app.remind'),
        ),
    ]
