# Generated by Django 4.1.5 on 2023-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_bot_app', '0012_alter_remind_day_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='day_repeat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
